# Generated by Django 4.0.3 on 2022-05-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chargily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('EDAHABIA', 'EDAHABIA'), ('CIB', 'CIB')], default='EDAHABIA', max_length=200)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
